apiVersion: v1
kind: Service
metadata:
  name: elk
  labels:
    app: axonius
spec:
  ports:
    - port: 5601
      name: kibana
    - port: 5043
      name: logstash
    - port: 9200
      name: elastic
  selector:
    app: axonius
    tier: system
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ax-elastic-pv-claim
  labels:
    app: axonius
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
