DEVICE_PER_PAGE = 200
MAX_NUMBER_OF_DEVICES = 20000000

DEFAULT_ASYNC_CHUNKS_SIZE = 50

URL_BASE_PREFIX = 'api'
TOKEN_API_URL_SUFFIX = 'SessionService/Sessions'
TOKEN_API_SESSION_TYPE = 'API'
DEVICE_API_URL_SUFFIX = 'DeviceService/Devices'
DEVICE_INVENTORY_API_URL_SUFFIX = f'{DEVICE_API_URL_SUFFIX}({{device_id}})/InventoryDetails'

EXTRA_INVENTORY = 'extra_inventory'
