version: '3'
services:
  mongodb:
        image: mongo
        container_name: "mongo"
        environment:
          - MONGO_INITDB_ROOT_USERNAME=ax_user
          - MONGO_INITDB_ROOT_PASSWORD=ax_pass
          - MONGO_INITDB_DATABASE=core
        volumes:
          - ./create_core_role.js:/docker-entrypoint-initdb.d/create_core_role.js
        ports:
            - 27017:27017


networks:
  default:
    external:
      name: axonius