apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent-storage
  labels:
    app: axonius
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi