DEVICE_PER_PAGE = 100
MAX_NUMBER_OF_USERS = 1000000
MAX_PAGES_GROUPS = 100
MAX_PAGES_PROJECTS = 100
MAX_PROJECT_COUNT = 1000


API_URL_PREFIX = 'api/v4'

GROUPS_PREFIX = 'groups'
EXTRA_GROUPS = 'extra_groups'
EXTRA_PROJECTS = 'extra_projects'
