from axonius.devices.device_adapter import DeviceAdapter
from axonius.fields import Field, ListField
from axonius.smart_json_class import SmartJsonClass
from axonius.users.user_adapter import UserAdapter
from axonius.utils import datetime


class CiIpData(SmartJsonClass):
    u_authorative_dns_name = Field(str, 'Authorative DNS Name')
    u_ip_version = Field(str, 'IP Version')
    u_ip_address = Field(str, 'IP Address')
    u_lease_contract = Field(str, 'Lease Contract')
    u_netmask = Field(str, 'Netmask')
    u_network_address = Field(str, 'Network Address')
    u_subnet = Field(str, 'Subnet')
    u_zone = Field(str, 'Zone')
    u_ip_address_property = Field(str, 'IP Address Property')
    u_ip_network_class = Field(str, 'IP Network Class')
    u_last_discovered = Field(datetime.datetime, 'Last Discovered')
    u_install_status = Field(str, 'Install Status')


class MaintenanceSchedule(SmartJsonClass):
    name = Field(str, 'Name')
    ms_type = Field(str, 'Type')
    description = Field(str, 'Description')
    document = Field(str, 'Document')
    document_key = Field(str, 'Document Key')


class RelativeInformationLeaf(SmartJsonClass):
    name = Field(str, 'Name')
    sys_class_name = Field(str, 'Class Name')


class RelativeInformationNode1(SmartJsonClass):
    name = Field(str, 'Name')
    sys_class_name = Field(str, 'Class Name')
    upstream = ListField(RelativeInformationLeaf, 'Upstream')
    downstream = ListField(RelativeInformationLeaf, 'Downstream')


class SnowUserAdapter(UserAdapter):
    snow_source = Field(str, 'ServiceNow Source')
    snow_roles = Field(str, 'Roles')
    updated_on = Field(datetime.datetime, 'Updated On')
    active = Field(str, 'Active')
    u_studio = Field(str, 'Studio')
    u_sub_department = Field(str, 'Subdepartment')
    u_saved_groups = ListField(str, 'Saved Groups')
    u_saved_roles = ListField(str, 'Saved Roles')
    u_profession = Field(str, 'Profession')
    u_company = Field(str, 'Company')
    u_department = Field(str, 'Department')
    u_vip = Field(bool, 'VIP')
    u_business_unit = Field(str, 'Business Unit')
    u_division = Field(str, 'Division')
    u_level1_mgmt_org_code = Field(str, 'Level 1 Management Org. Code')
    u_level2_mgmt_org_code = Field(str, 'Level 2 Management Org. Code')
    u_level3_mgmt_org_code = Field(str, 'Level 3 Management Org. Code')
    u_pg_email_address = Field(str, 'PG Email Address')


class SnowComplianceException(SmartJsonClass):
    exception_id = Field(str, 'ID')
    policy_name = Field(str, 'Policy Name')
    policy_statement = Field(str, 'Policy Statement')
    issue = Field(str, 'Issue')
    opened_by = Field(str, 'Opened By')
    short_description = Field(str, 'Short Description')
    state = Field(str, 'State')
    substate = Field(str, 'Substate')
    valid_to = Field(datetime.datetime, 'Valid To')
    assignment_group = Field(str, 'Assignment Group')


class SnowDeviceContract(SmartJsonClass):
    number = Field(str, 'Number')
    short_desc = Field(str, 'Short Description')
    parent_number = Field(str, 'Parent Number')


class SnowDeviceAdapter(DeviceAdapter):
    sys_id = Field(str, 'Sys Id')
    table_type = Field(str, 'Table Type')
    category = Field(str, 'Category')
    u_subcategory = Field(str, 'Subcategory')
    asset_tag = Field(str, 'Asset Tag')
    class_name = Field(str, 'Class Name')
    discovery_source = Field(str, 'Discovery Source')
    last_discovered = Field(datetime.datetime, 'Last Discovered')
    first_discovered = Field(datetime.datetime, 'First Discovered')
    snow_location = Field(str, 'Location')
    snow_department = Field(str, 'Department')
    fqdn = Field(str, 'Fully Qualified Domain Name')
    assigned_to = Field(str, 'Assigned To')
    install_status = Field(str, 'Install Status')
    assigned_to_location = Field(str, 'Assigned To Location')
    assigned_to_country = Field(str, 'Assigned To Country')
    assigned_to_division = Field(str, 'Assigned To Division')
    assigned_to_business_unit = Field(str, 'Assigned To Business Unit')
    manager_email = Field(str, 'Manager Email')
    u_business_unit = Field(str, 'Business Unit')
    purchase_date = Field(datetime.datetime, 'Purchase date')
    substatus = Field(str, 'Substatus')
    u_shared = Field(str, 'Shared')
    u_loaner = Field(str, 'Loaner')
    u_virtual_system_type = Field(str, 'Virtual System Type')
    u_cloud_premises = Field(str, 'Cloud Premises')
    u_bia_confidentiality = Field(str, 'BIA Confidentiality')
    u_bia_availability = Field(str, 'BIA Availability')
    u_bia_id = Field(str, 'BIA ID')
    u_bia_integrity = Field(str, 'BIA Integrity')
    u_bia_overall = Field(str, 'BIA Overall')
    u_casper_status = Field(str, 'Casper Status')
    u_cloud_deployment_model = Field(str, 'Cloud Deployment Model')
    u_cloud_hosted = Field(str, 'Cloud Hosted')
    u_cloud_service_type = Field(str, 'Cloud Service Type')
    u_crosssite_condition = Field(str, 'Cross site Condition')
    u_heritage = Field(str, 'Heritage')
    u_altiris_status = Field(str, 'Altiris Status')
    first_deployed = Field(datetime.datetime, 'First Deployed')
    created_at = Field(datetime.datetime, 'Created At')
    created_by = Field(str, 'Created By')
    sys_updated_on = Field(str, 'Updated On')
    used_for = Field(str, 'Used For')
    tenable_asset_group = Field(str, 'Tenable Asset Group')
    environment = Field(str, 'Environment')
    cmdb_business_function = Field(str, 'Business Function')
    management_ip = Field(str, 'Management IP')
    end_of_support = Field(str, 'End Of Support')
    firmware_version = Field(str, 'Firmware Version')
    model_version_number = Field(str, 'Model Version Number')
    operational_status = Field(str, 'Operational Status')
    hardware_status = Field(str, 'Hardware Status')
    hardware_substatus = Field(str, 'Hardware Substatus')
    vendor = Field(str, 'Vendor')
    u_vendor_ban = Field(str, 'Vendor Ban')
    u_number = Field(str, 'U Number')
    support_group = Field(str, 'Support Group')
    u_director = Field(str, 'Director')
    u_manager = Field(str, 'Manager')
    is_virtual = Field(bool, 'Is Virtual')
    ci_ips = ListField(CiIpData, 'CI IP Data')
    u_supplier = Field(str, 'Supplier')
    u_business_segment = Field(str, 'Business Segment')
    u_consumption_type = Field(str, 'Consumption Type')
    u_function = Field(str, 'Function')
    u_ge_data_class = Field(str, 'GE Data Class')
    u_location_details = Field(str, 'Location Details')
    u_management_access_address = Field(str, 'Management Access Address')
    u_management_access_type = Field(str, 'Management Access Type')
    u_network_zone = Field(str, 'Network Zone')
    maintenance_schedule = Field(MaintenanceSchedule, 'Maintenance Schedule')
    company = Field(str, 'Company')
    model_u_classification = Field(str, 'Model Classification')
    u_alias = Field(str, 'Alias')
    use_count = Field(int, 'Use Count')
    use_units = Field(str, 'Use Units')
    bandwidth = Field(int, 'Estimated bandwidth')
    snmp_sys_location = Field(str, 'SNMP Location')
    u_audit_tools_checked = Field(str, 'Audit Tools Checked')
    u_audit_tools_pass = Field(str, 'Audit Tools Pass')
    u_backbone = Field(str, 'Backbone')
    u_bill_ref_id = Field(str, 'Bill Ref ID')
    u_circuit_id = Field(str, 'Circuit ID')
    u_config_item_id = Field(str, 'Config Item ID')
    u_ownership_ack = Field(str, 'Ownership ACK')
    u_port_speed = Field(str, 'Port Speed')
    u_previous_assigned_to = Field(str, 'Previous Assigned To')
    u_previous_owned_by = Field(str, 'Previous Owned By')
    u_process_origin = Field(str, 'Process Origin')
    u_system_origin = Field(str, 'System Origin')
    u_uninstall_date = Field(datetime.datetime, 'Uninstall Date')
    u_access_authorisers = Field(str, 'Access Authorisers')
    u_access_control_list_extraction_method = Field(str, 'ACL Extraction Method')
    u_acl_contacts = Field(str, 'ACL Contacts')
    u_acl_contacts_mailbox = Field(str, 'ACL Contacts Mailbox')
    u_atm_category = Field(str, 'ATM Category')
    u_atm_line_address = Field(str, 'ATM Line Address')
    u_atm_security_carrier = Field(str, 'ATM Security Carrier')
    u_attestation_date = Field(datetime.datetime, 'Attestation Date')
    u_bted_id = Field(str, 'BTED ID')
    u_bucf_contacts = Field(str, 'BUCF Contacts')
    u_bucf_contacts_mailbox = Field(str, 'BUCF Contacts Mailbox')
    u_business_owner = Field(str, 'Business Owner')
    u_cmdb_data_mgt_journal = Field(str, 'Management Journal')
    u_cmdb_data_owner = Field(str, 'Data Owner')
    u_cmdb_data_owner_group = Field(str, 'Data Owner Group')
    u_cmdb_data_owner_team = Field(str, 'Data Owner Team')
    u_cmdb_data_steward = Field(str, 'Data Steward')
    u_custodian = Field(str, 'Custodian')
    u_custodian_group = Field(str, 'Custodian Group')
    u_custodian_team = Field(str, 'Custodian Team')
    u_delivery_of_access_control_list = Field(str, 'Delivery of ACL')
    u_fulfilment_group = Field(str, 'Fulfilment Group')
    u_last_update_from_import = Field(str, 'Last Update From Import')
    u_oim_division = Field(str, 'OIM Division')
    u_organisation = Field(str, 'Organisation')
    u_orphan_account_contacts = Field(str, 'Orphan Account Contacts')
    u_orphan_account_manager = Field(str, 'Orphan Account Manager')
    u_permitted_childless = Field(str, 'Permitted Childless')
    u_permitted_parentless = Field(str, 'Permitted Parentless')
    u_primary_support_group = Field(str, 'Primary Support Group')
    u_primary_support_sme = Field(str, 'Primary Support SME')
    u_primary_support_team = Field(str, 'Primary Support Team')
    u_reason_for_childless = Field(str, 'Reason For Childless')
    u_reason_for_parentless = Field(str, 'Reason For Parentless')
    u_recertification_approach = Field(str, 'Recertification Approach')
    u_recertification_contacts = Field(str, 'Recertification Contacts')
    u_recertification_type = Field(str, 'Recertification Type')
    u_record_date_time = Field(str, 'Record Date Time')
    u_record_id = Field(str, 'Record ID')
    u_record_name = Field(str, 'Record Name')
    u_ref_1_label = Field(str, 'Ref 1 Label')
    u_ref_1_value = Field(str, 'Ref 1 Value')
    u_ref_2_label = Field(str, 'Ref 2 Label')
    u_ref_2_value = Field(str, 'Ref 2 Value')
    u_ref_3_label = Field(str, 'Ref 3 Label')
    u_ref_3_value = Field(str, 'Ref 3 Value')
    u_role = Field(str, 'Role')
    u_security_administrators = Field(str, 'Security Administrators')
    u_si_id = Field(str, 'SI ID')
    u_source_name = Field(str, 'Source Name')
    u_source_target_class = Field(str, 'Source Target Class')
    u_sox_control = Field(str, 'SOX Control')
    u_suspensions_deletions = Field(str, 'Suspensions Deletions')
    u_technical_admin_contacts = Field(str, 'Technical Admin Contacts')
    u_tech_admin_mailbox = Field(str, 'Tech Admin Mailbox')
    u_toxic_division_group = Field(str, 'Toxic Division Group')
    u_uar_contacts = Field(str, 'UAR Contacts')
    u_uar_contacts_mailbox = Field(str, 'UAR Contacts Mailbox')
    u_uav_delegates = Field(str, 'UAV Delegates')
    u_work_notes = Field(str, 'Work Notes')
    phone_number = Field(str, 'Phone Number')
    ci_comm_type = Field(str, 'Type')
    u_it_owner_organization = Field(str, 'IT Owner Organization')
    u_managed_by_vendor = Field(str, 'Managed By Vendor')
    u_division = Field(str, 'Division')
    u_level1_mgmt_org_code = Field(str, 'Level 1 Management Org. Code')
    u_level2_mgmt_org_code = Field(str, 'Level 2 Management Org. Code')
    u_level3_mgmt_org_code = Field(str, 'Level 3 Management Org. Code')
    u_pg_email_address = Field(str, 'PG Email Address')
    u_last_inventory = Field(datetime.datetime, 'Last Inventory')
    verification_install_status = Field(str, 'Verification Install Status')
    verification_operational_status = Field(str, 'Verification Operational Status')
    compliance_exceptions = ListField(SnowComplianceException, 'Compliance Exceptions')
    contracts = ListField(SnowDeviceContract, 'Contracts')
    diversiture_contracts = ListField(SnowDeviceContract, 'Diversiture Contracts')
    # you should keep these last
    upstream = ListField(RelativeInformationNode1, 'Upstream')
    downstream = ListField(RelativeInformationNode1, 'Downstream')
