COMPUTER_DEVICE_TYPE = 'computer'
COMPUTER_HISTORY_URL = 'computerhistory/id/'
COMPUTERS_URL = 'computers'
COMPUTERS_DEVICE_LIST_NAME = 'computers'
COMPUTER_HISTORY_XML_NAME = 'computer_history'
MOBILE_DEVICE_URL = 'mobiledevices'
MOBILE_DEVICE_LIST_NAME = 'mobile_devices'
MOBILE_DEVICE_TYPE = 'mobile_device'
COMPUTER_HISTORY_POLICY_LIST_NAME = 'policy_logs'
COMPUTER_HISTORY_POLICY_INFO_TYPE = 'policy_log'

USERNAME = 'username'
JAMF_DOMAIN = 'Jamf_Domain'
PASSWORD = 'password'
HTTP_PROXY = 'http_proxy'
HTTPS_PROXY = 'https_proxy'

DEFAULT_FETCH_DEPARTMENT = False
DEFAULT_SHOULD_FETCH_POLICIES = True
DEFAULT_NUM_OF_THREADS = 15
DEFAULT_SHOULD_NOT_KEEPALIVE = False
DEFAULT_THREADS_TIME_SLEEP = 1
