<template>
    <scrollable-page :breadcrumbs="[
    	{ title: 'plugins', path: { name: 'Plugins'}},
    	{ title: pluginDisplayName }
    ]">
        <div class="plugin-config">
            <div class="container"><!-- (Left part of the screen) Preparing the plugin -->
                <div class="row">
                    <div class="form-group col">
                        <div class="form-group-header">
                            <svg-icon name="actions/info" height="28" :original="true"></svg-icon>
                            <span class="form-group-title">Plugin Info</span>
                        </div>
                        <div class="ml-4 mt-2">{{ pluginDescription }}</div>
                    </div>
                </div>
                <div class="row row-divider">
                    <div class="form-group col">
                        <div class="form-group-header">
                            <svg-icon name="actions/settings" height="28" :original="true"></svg-icon>
                            <span class="form-group-title">Settings</span>
                        </div>
                        <div class="ml-4 mt-2">
                            <div>The following settings affect the behavior of the plugin.</div>
                            <label class="form-label" for="pluginInterval">Plugin Run Interval:</label>
                            <input class="form-control" id="pluginInterval" :disabled="true" value="12 hours">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group btn-group">
                        <a class="btn success-fill" @click="startPlugin(uniquePluginName)"
                           v-if="pluginData.state === 'Disabled'">run plugin</a>
                        <a class="btn" @click="stopPlugin(uniquePluginName)" v-else>stop plugin</a>
                    </div>
                </div>
            </div>
            <div class="bubble ml-4"><!-- (Right part of the screen) Viewing results generated by plugin -->
                <div class="title">Current Results</div>
                <div class="summary mt-4 mb-4">
                    <svg-icon name="actions/get_msg" height="28" :original="true"></svg-icon>
                    <span class="mr-2">AXONIUS</span>
                    <span v-if="pluginData.results.length">Reports {{ pluginData.results.length }}
                        Devices have conflicting IP identity</span>
                    <span v-else-if="pluginData.state === 'Disabled'">insights</span>
                </div>
                <table class="table" v-if="pluginData.results.length">
                    <thead>
                    <th>Axonius Name</th>
                    <th>Host Name</th>
                    <th>IP Conflicts</th>
                    </thead>
                    <tbody>
                    <tr v-for="result in pluginData.results" v-bind:class="{'active': openResult == result.uuid }">
                        <td>{{result.adapters[0].data.pretty_id}}</td>
                        <td>{{result.adapters[0].data.hostname}}</td>
                        <td @mouseenter="openResult = result.uuid" @mouseleave="openResult = ''">
                            {{result.conflicts.length}} IPs found for this device
                            <div v-if="result.conflicts.length" v-show="openResult === result.uuid" class="bubble-mini">
                                <div class="row header mt-2">
                                    <div class="col">IP Address</div>
                                    <div class="col">Server Name</div>
                                </div>
                                <div v-for="conflict in result.conflicts" class="row row-divider">
                                    <div class="col">{{conflict.ip}}</div>
                                    <div class="col">{{conflict.server}}</div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </scrollable-page>
</template>


<script>
	import ScrollablePage from '../../components/ScrollablePage.vue'
	import PaginatedTable from '../../components/ScrollableTable.vue'
	import InfoDialog from '../../components/InfoDialog.vue'
	import ToggleButton from 'vue-js-toggle-button'
	import VueCharts from 'vue-charts'
	import Vue from 'vue'
	import axios from 'axios'

	import { mapState, mapGetters, mapActions } from 'vuex'
	import { FETCH_PLUGIN, pluginStaticData, START_PLUGIN, STOP_PLUGIN } from '../../store/modules/plugin'
	import '../../components/icons/action'

	export default {
		name: 'plugins-config-container',
		components: {ScrollablePage, PaginatedTable, InfoDialog},
		data: function () {
			return {
				openResult: ''
            }
		},
		computed: {
			...mapState(['plugin']),
			uniquePluginName () {
				return this.$route.params.id
			},
			pluginName () {
				return this.uniquePluginName.match(/(.*[_-]plugin)[_-]?\d*/)[1]
			},
			pluginDisplayName () {
				if (!pluginStaticData[this.pluginName]) { return }
				return pluginStaticData[this.pluginName].name
			},
			pluginDescription () {
				if (!pluginStaticData[this.pluginName]) { return }
				return pluginStaticData[this.pluginName].description
			},
			pluginData () {
				return this.plugin.currentPlugin.data
			}
		},
		methods: {
			...mapActions({
				fetchPlugin: FETCH_PLUGIN,
				startPlugin: START_PLUGIN,
				stopPlugin: STOP_PLUGIN
			})
		},
		created () {
			if (!this.pluginData || !this.pluginData.schema) {
				this.fetchPlugin(this.uniquePluginName)
			}
		}
	}
</script>


<style lang="scss">
    @import '../../scss/config';

    .plugin-config {
        display: flex;
        .container {
            width: 40vw;
        }
        .bubble {
            width: 60vw;
            padding: 24px;
            border-radius: 4px;
            background-color: $background-color-light;
            box-shadow: -1px 1px 4px 0px $border-color;
            .summary {
                padding: 12px;
                border: 2px dashed $border-color;
                span {
                    vertical-align: middle;
                }
            }
            .table {
                font-weight: 200;
                cursor: default;
                tr {
                    &.active {
                        td {
                            background-color: $background-color-hover;
                        }
                    }
                    td {
                        position: relative;
                        .bubble-mini {
                            font-size: 14px;
                            position: absolute;
                            border-radius: 4px;
                            box-shadow: -1px 1px 4px 2px $border-color;
                            background-color: $background-color-light;
                            z-index: 10;
                            top: 50px;
                            width: 100%;
                            &::before {
                                content: '';
                                height: 0;
                                position: absolute;
                                top: -12px;
                                border-left: 24px solid transparent;
                                border-right: 24px solid transparent;
                                border-bottom: 12px solid white;
                                left: 2px;
                            }
                            .header {
                                font-weight: 400;
                            }
                            .row {
                                margin-left: 12px;
                                margin-right: 12px;
                                &.row-divider {
                                    padding: 8px 0;
                                }
                                .col {
                                    padding: 0;
                                }
                            }
                        }
                    }
                }
            }
        }
        .form-group.btn-group {
            text-align: center;
            width: 100%;
            .btn {
                margin: auto;
                width: 240px;
            }
        }
    }
</style>