/* eslint-disable */
require('./adapter')
require('./alert')
require('./dashboard')
require('./device')
require('./logout')
require('./menu')
require('./notifications')
require('./plugin')
require('./report')
require('./settings')
require('./task')
require('./user')
