version: '3'
services:
  puppet-adapter:
        build: .
        image: axonius/puppet-adapter
        container_name: "puppet-adapter"
        ports:
            - 5222:80
        volumes:
          - ../../logs/puppet-adapter:/home/axonius/logs
          - data:/home/axonius

volumes:
  data:

networks:
  default:
    external:
      name: axonius