apiVersion: v1
kind: Service
metadata:
  name: core
  labels:
    app: axonius
spec:
  ports:
    - port: 80
  selector:
    app: axonius
    tier: frontend
  type: LoadBalancer
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: ax-core-pv-claim
#  labels:
#    app: axonius
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 5Gi
