DEVICE_PER_PAGE = 200
MAX_NUMBER_OF_DEVICES = 20000000

TOKEN_GRANT_TYPE = 'password'
TOKEN_TYPE_REFRESH_TYPE = 'refresh_token'
DEFAULT_TOKEN_REFRESH_TIME = 7200  # Seconds -> 2 Hours -> 120 Minutes

API_BASE_PREFIX = 'v1'
GET_TOKEN_URL_SUFFIX = 'oauth2/token'
REFRESH_TOKEN_URL_SUFFIX = 'oauth2/refreshToken'
SWITCH_API_SUFFIX = 'switches'
