PAGE_SIZE = 500
MAX_DEVICES_NUMBER = 2000000
MAX_APPS_NUMBER = 10000
ENROLLED_DEVICE = 'Enrolled Device'
NOT_ENROLLED_DEVICE = 'Not Enrolled Device'
DEVICE_EXTENDED_INFO_KEY = 'DeviceExtendedInfo'

DEVICES_ENDPOINT = 'mdm/devices'
APPS_SUBENDPOINT = 'apps'
NETWORK_SUBENDPOINT = 'network'
NOTES_SUBENDPOINT = 'notes'
TAGS_SUBENDPOINT = 'tags'
PROFILES_SUBENDPOINT = 'profiles'
ERROR_MUTED_SUBENDPOINTS = [TAGS_SUBENDPOINT, PROFILES_SUBENDPOINT, NOTES_SUBENDPOINT]
