/* eslint-disable */
require('./error')
require('./failure')
require('./funnel')
require('./histogram')
require('./info')
require('./line')
require('./pie')
require('./post')
require('./running')
require('./success')
require('./summary')
require('./troffy')
require('./warning')
