/* eslint-disable */
require('./adapters')
require('./dashboard')
require('./devices')
require('./enforcements')
require('./instances')
require('./logout')
require('./menu')
require('./notifications')
require('./pairing')
require('./reports')
require('./settings')
require('./users')
