/* eslint-disable */
require('./adapter')
require('./alert')
require('./dashboard')
require('./devices')
require('./instances')
require('./pairing')
require('./logout')
require('./menu')
require('./notifications')
require('./report')
require('./settings')
require('./users')
