MAX_NUMBER_OF_PAGES = 20000
RESULTS_PER_PAGE = 1000
LEASE_TYPE = 'DHCP LEASE'
A_TYPE = 'A Record'
ADDRESS_TYPE = 'Address'

DEFAULT_FETCH_LEASE = True
DEFAULT_FETCH_USED_ADDR = False
DEFAULT_FETCH_A_RECORDS = False
