DEVICE_PER_PAGE = 50
MAX_NUMBER_OF_DEVICES = 2000000

PAGINATION_FIELD_PAGE_NUMBERS = 'page'

AWS_INSTANCE = 'AwsInstance'
ENDPOINTS_ASSETS = [AWS_INSTANCE]

DEFAULT_CLOUD_HEALTH_DOMAIN = 'https://chapi.cloudhealthtech.com'
CLOUD_HEALTH_DOMAIN_API = f'{DEFAULT_CLOUD_HEALTH_DOMAIN}/api'
