DOCKER_PORTS = {
    'gui':                              80,
    'execution':                        4999,
    'aggregator':                       5000,
    'ad-adapter':                       5001,
    'watch':                            5002,
    'epo-adapter':                      5003,
    'jamf-adapter':                     5004,
    'correlator':                       5009,
    'static-correlator':                5010,
    'dns-conflicts':                    5011,
    'nexpose-adapter':                  5012,
    'csv-adapter':                      5013,
    'qcore-adapter':                    5015,
    'qcore-mediator':                   5016,
    'careful-execution-correlator':     5039,
    'core':                             5050,
    'esx-adapter':                      5111,
    'aws-adapter':                      5112,
    'traiana-lab-machines-adapter':     5113,
    'stresstest-adapter':               5114,
    'puppet-adapter':                   5222,
    'nessus-adapter':                   5555,
    'general-info':                     5556,
    'symantec-adapter':                 5676,
    'qualys-adapter':                   5677,
    'sentinelone-adapter':              5678,
    'splunk-symantec-adapter':          5679,
    'splunk-nexpose-adapter':           5681,
    'eset-adapter':                     5682,
    'fortigate-adapter':                5689,
    'sccm-adapter':                     5699,
    'qualys-scans-adapter':             5777,
    'cisco-adapter':                    6001,
    'mongo':                            27017,
}

assert len(set(DOCKER_PORTS.values())) == len(DOCKER_PORTS)
