apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ad-dapter
  labels:
    app: axonius
spec:
  selector:
    matchLabels:
      app: axonius
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: axonius
        tier: frontend
    spec:
      containers:
      - image: 405773942477.dkr.ecr.us-east-2.amazonaws.com/axonius/ad-adapter
        name: ad-adapter
        imagePullPolicy: Never # TODO: Change to IfNotPresent or Always after aws vpc with default dhcp fix.
        ports:
        - containerPort: 5000
          name: ad-dapter
#        volumeMounts:
#        - name: axonius-logs
#          mountPath: /log
#      nodeSelector:
#        ax_type: "cloud" # TODO: Make's it run on a specific node (this case master), Should move this implementation to gui service.
#      volumes:
#      - name: axonius-logs
#        persistentVolumeClaim:
#          claimName: ax-core-pv-claim
