DEVICE_PER_PAGE = 200
MAX_NUMBER_OF_DEVICES = 20000000

URL_BASE_PREFIX = 'rest/api/1.0'
PROJECTS_SUFFIX = 'projects'
REPOS_SUFFIX = f'{PROJECTS_SUFFIX}/{{project_name}}/repos'
COMMITS_SUFFIX = '{repo_suffix}/commits'
DEFAULT_MAX_COMMITS = 50
MAXIMUM_FOR_MAX_COMMITS = 1000
