SKIP_DEPLOYMENT_MARKER = 'deploy_skip.marker'

FILENAMES_EXCLUDE_GLOBAL = ['.git',
                            '.idea',
                            '.cache',
                            '__pycache__',
                            'tests',
                            'adapters/debug_main.py',
                            'plugins/debug_main.py',
                            'deployment/make.py',
                            'deployment/run_tests.py',
                            'deployment/run_tests.sh',
                            'clean_dockers.sh',
                            'download_artifacts.sh',
                            'get_ready.sh',
                            'devops/prepare_setup.py',
                            'devops/scripts/host_installation/init_host.sh',
                            'prepare_ci_env.sh',
                            'run_basic_tests.sh',
                            'run_nightly_tests.sh',
                            'run_sanity_tests.sh',
                            'run_tests.sh',
                            'run_ui_tests.sh',
                            'run_upgrade_tests.sh',
                            'run_ut_tests.sh',
                            'setup_tests.sh',
                            'tests.sh',
                            'wait-apt-get.sh', ]
DIRS_EXCLUDE_GLOBAL = ['venv',
                       'logs',
                       'devops/systemization',
                       'devops/CI',
                       'deploy_artifacts',
                       'plugins/gui/frontend/node_modules',
                       'plugins/gui/frontend/dist',
                       'testing/test_credentials']

OLD_CRONJOBS = ['restart_system_on_reboot', 'start_system_on_first_boot']
