from axonius.fields import Field
from axonius.users.user_adapter import UserAdapter


class BeyondTrustPrivilegedIdentityUserInstance(UserAdapter):
    alert_on_recovery = Field(bool, 'Alert On Recovery')
    alert_on_request = Field(bool, 'Alert On Request')
    domain_account = Field(str, 'Domain Account')
    permission_access_remote_sessions = Field(bool, 'Permission Access Remote Sessions')
    permission_add_passwords_for_managed_systems = Field(bool, 'Permission Add Passwords For Managed Systems')
    permission_all_access = Field(bool, 'Permission All Access')
    permission_create_refresh_system_job = Field(bool, 'Permission Create Refresh System Job')
    permission_edit_delegation = Field(bool, 'Permission Edit Delegation')
    permission_edit_password_lists = Field(bool, 'Permission Edit Password Lists')
    permission_edit_stored_passwords = Field(bool, 'Permission Edit Stored Passwords')
    permission_elevate_account_permissions = Field(bool, 'Permission Elevate Account Permissions')
    permission_elevate_any_account_permissions = Field(bool, 'Permission Elevate Any Account Permissions')
    permission_grant_password_requests = Field(bool, 'Permission Grant Password Requests')
    permission_ignore_password_checkout = Field(bool, 'Permission Ignore Password Checkout')
    permission_logon = Field(bool, 'Permission Logon')
    permission_personal_store = Field(bool, 'Permission Personal Store')
    permission_request_passwords = Field(bool, 'Permission Request Passwords')
    permission_request_remote_access = Field(bool, 'Permission Request Remote Access')
    permission_require_oath = Field(bool, 'Permission Require OATH')
    permission_require_rsa_secure_id = Field(bool, 'Permission Require RSA Secure ID')
    permission_self_recovery = Field(bool, 'Permission Self Recovery')
    permission_view_accounts = Field(bool, 'Permission View Accounts')
    permission_view_dashboards = Field(bool, 'Permission View Dashboards')
    permission_view_delegation = Field(bool, 'Permission View Delegation')
    permission_view_file_store = Field(bool, 'Permission View File Store')
    permission_view_jobs = Field(bool, 'Permission View Jobs')
    permission_view_password_activity = Field(bool, 'Permission View Password Activity')
    permission_view_password_history = Field(bool, 'Permission View Password History')
    permission_view_passwords = Field(bool, 'Permission View Passwords')
    permission_view_scheduler = Field(bool, 'Permission View Scheduler')
    permission_view_systems = Field(bool, 'Permission View Systems')
    permission_view_web_logs = Field(bool, 'Permission View Web Logs')
