PASSWORD = 'password'
USER = 'username'
FORTIGATE_HOST = 'host'
FORTIGATE_PORT = 'port'
DEFAULT_FORTIGATE_PORT = 443
VERIFY_SSL = 'verify_ssl'
VDOM = 'vdom'
DHCP_LEASE_TIME = 'dhcp_lease_time'  # In Seconds
DEFAULT_DHCP_LEASE_TIME = 604800
IS_FORTIMANAGER = 'is_fortimanager'
URL_PATH = 'jsonrpc'
EXEC_ID = 11
LOGIN_URL = 'sys/login/user'
DEVICES_URL = 'dvmdb'
GET_DEVICES_ID = 8625
GET_ADOMS_URL = 'dvmdb/adom'
GET_ADOMS_ID = 4321
