version: '3'
services:
  symantec-adapter:
        build: .
        image: axonius/symantec-adapter
        container_name: "symantec-adapter"
        ports:
            - 5676:80
        volumes:
          - ../../logs/symantec-adapter:/home/axonius/logs
          - data:/home/axonius

volumes:
  data:

networks:
  default:
    external:
      name: axonius