---
services:
    device_management:
        service_name: 'device-management'
        url: '/api/juniper/servicenow/device-management'

    device_group_management:
        service_name: 'device-group-management'
        url: '/api/juniper/servicenow/device-group-management'

    event_profile_management:
        service_name: 'event-profile-management'
        url: '/api/juniper/servicenow/event-profile-management'
...