# AWS Confiurations
import os
import ast

# AWS Configuration
AWS_REGULAR_INSTANCE_SUBNET_ID = os.environ.get('AWS_REGULAR_INSTANCE_SUBNET_ID')
AWS_REGULAR_INSTANCE_SECURITY_GROUPS = ast.literal_eval(os.environ.get('AWS_REGULAR_INSTANCE_SECURITY_GROUPS'))
AWS_REGULAR_INSTANCE_DEFAULT_HD_SIZE = ast.literal_eval(os.environ.get('AWS_REGULAR_INSTANCE_DEFAULT_HD_SIZE'))
AWS_REGULAR_INSTANCE_NO_INTERNET_SG = ast.literal_eval(os.environ.get('AWS_REGULAR_INSTANCE_NO_INTERNET_SG'))
AWS_PUBLIC_INSTANCE_SUBNET_ID = os.environ.get('AWS_PUBLIC_INSTANCE_SUBNET_ID')
AWS_PUBLIC_INSTANCE_SECURITY_GROUPS = ast.literal_eval(os.environ.get('AWS_PUBLIC_INSTANCE_SECURITY_GROUPS'))
AWS_UBUNTU_VANILLA_IMAGE_ID = os.environ.get('AWS_UBUNTU_VANILLA_IMAGE_ID')

# GCP Configurations
GCP_UBUNTU_VANILLA_IMAGE_ID = os.environ.get('GCP_UBUNTU_VANILLA_IMAGE_ID')
GCP_DEFAULT_REGION = os.environ.get('GCP_DEFAULT_REGION')
GCP_DFEAULT_ZONE = os.environ.get('GCP_DFEAULT_ZONE')


GCP_REGULAR_INSTANCE_NETWORK_ID = os.environ.get('GCP_REGULAR_INSTANCE_NETWORK_ID')
GCP_REGULAR_INSTANCE_SUBNETWORK_ID = os.environ.get('GCP_REGULAR_INSTANCE_SUBNETWORK_ID')
GCP_REGULAR_INSTANCE_DEFAULT_HD_SIZE = ast.literal_eval(os.environ.get('GCP_REGULAR_INSTANCE_DEFAULT_HD_SIZE'))
GCP_PUBLIC_INSTANCE_NETWORK_ID = os.environ.get('GCP_PUBLIC_INSTANCE_NETWORK_ID')
GCP_PUBLIC_INSTANCE_SUBNETWORK_ID = os.environ.get('GCP_PUBLIC_INSTANCE_SUBNETWORK_ID')


NO_INTERNET_NETWORK_SECURITY_OPTION = os.environ.get('NO_INTERNET_NETWORK_SECURITY_OPTION')

# Public Keys
# Note that while we can reference keys only by their name in AWS, in GCP we have to provide the actual
# public key.
CLOUD_DEFAULT_KEY = 'Builds-VM-Key'
CLOUD_KEYS = {
    'Builds-VM-Key': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC80rvBim1vAk33niXguzFHa1B/zBjrQN2gzqdrNMt8WuTJLh30PYn24IPqfbfndGN02Ao4QHRp+f+IjcxQLVFHCLwjSKk4Euv1xYPbqy1/BCuENxBbpt60Ckb7NOrCcWcvyNrf8UPggVc0xHSawe/1Gc8ySQKkD6oOwNkXO3LcMjvEBVlN33vqmbaO4Bo/fMZZ0QLYJcTh1a/78TnlfAbejXEn3e+3x0bEJIWPO4gVKKDYSR+PfsEZG1KAIrrYenbWU5aL0sjlWOSQGbQQpXVfM5HCubSp7EBQYHSC/cThK+Ozw3la+dfqG/YZpfZ4xzS9zb2bgk/YE+Xq/W0ZyVFJ',
    'Auto-Test-VM-Key': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCAuQYKtH1ztofXjhKa2hkWGOcT1HNX0EQlxyoKOjhF7lnnQgwilBWrWI/4OEYQHkIMkqf9IJZXXaoxPR5zxxcc1acBVOiEQQusqN20YANYGJIrt1mlafdhz/xoS/2Mgq8exXNw9BPWkziObMJNy/vOicFV5h6Eo5swRDxEF8xMUIrihlcy4YMBTUIDWggpA1yydim/CtQPq1IxWjmOy8W43WBbtwvLIhK+x6K1yBT6W5BgWDy2lQEBZbtWmEoTfqQAUVj7xoFIoDFpndoLqVPC6Agvw+i9VeJdi0wTi3Wii4hjP4DPtRwIn+htqoDOdIX5bsjQLC0rCkxZiQT3dh7b'
}
