DEVICE_PER_PAGE = 200
MAX_NUMBER_OF_DEVICES = 2000000
MAX_NUMBER_OF_USERS = 1000000

API_PREFIX = 'ipa/session'
API_LOGIN_PREFIX = 'login_password'
API_JSON_PREFIX = 'json'

HOSTS_METHOD = 'host_find'
USERS_METHOD = 'user_find'
STAGE_USERS_METHOD = 'stageuser_find'
USERS_METHODS = [USERS_METHOD, STAGE_USERS_METHOD]
