version: '3'
services:
  ad-adapter:
        build: .
        image: axonius/ad-adapter
        container_name: "ad-adapter"
        ports:
            - 5001:80
        volumes:
          - ../../logs:/home/axonius/logs
          - data:/home/axonius

volumes:
  data:

networks:
  default:
    external:
      name: axonius