
LABELS_CATALOG = {

    'permissions.settings': 'System and User Management',
    'permissions.settings.get': 'View system settings',
    'permissions.settings.get_users_and_roles': 'View user accounts and roles',
    'permissions.settings.users.put': 'Add user',
    'permissions.settings.users.post': 'Edit users',
    'permissions.settings.roles.put': 'Add role',
    'permissions.settings.users.delete': 'Delete user',
    'permissions.settings.roles.post': 'Edit roles',
    'permissions.settings.roles.delete': 'Delete role',
    'permissions.settings.reset_api_key': 'Reset API Key',
    'permissions.settings.post': 'Update system settings',
    'permissions.settings.run_manual_discovery': 'Run manual discovery cycle',
    'permissions.settings.audit.get': 'View Activity Logs',

    'permissions.dashboard': 'Dashboard',
    'permissions.dashboard.get': 'View dashboard',
    'permissions.dashboard.charts.delete': 'Delete chart',
    'permissions.dashboard.charts.put': 'Add chart',
    'permissions.dashboard.charts.post': 'Edit charts',
    'permissions.dashboard.spaces.put': 'Add and edit spaces',
    'permissions.dashboard.spaces.delete': 'Delete space',

    'permissions.devices_assets': 'Device Assets',
    'permissions.devices_assets.get': 'View devices',
    'permissions.devices_assets.post': 'Edit devices',
    'permissions.devices_assets.saved_queries.run': 'Run saved queries',
    'permissions.devices_assets.saved_queries.post': 'Edit saved queries',
    'permissions.devices_assets.saved_queries.delete': 'Delete saved query',
    'permissions.devices_assets.saved_queries.put': 'Create saved query',

    'permissions.users_assets': 'User Assets',
    'permissions.users_assets.get': 'View users',
    'permissions.users_assets.post': 'Edit users',
    'permissions.users_assets.saved_queries.run': 'Run saved queries',
    'permissions.users_assets.saved_queries.post': 'Edit saved queries',
    'permissions.users_assets.saved_queries.delete': 'Delete saved query',
    'permissions.users_assets.saved_queries.put': 'Create saved query',

    'permissions.reports': 'Reports',
    'permissions.reports.get': 'View reports',
    'permissions.reports.put': 'Add report',
    'permissions.reports.post': 'Edit reports',
    'permissions.reports.delete': 'Delete report',
    'permissions.reports.private': 'Use private reports',

    'permissions.instances': 'Instances',
    'permissions.instances.get': 'View instances',
    'permissions.instances.post': 'Edit instance',

    'permissions.adapters': 'Adapters',
    'permissions.adapters.get': 'View adapters',
    'permissions.adapters.connections.put': 'Add connection',
    'permissions.adapters.connections.post': 'Edit connections',
    'permissions.adapters.post': 'Edit adapter advanced settings',
    'permissions.adapters.connections.delete': 'Delete connection',

    'permissions.enforcements': 'Enforcement Center',
    'permissions.enforcements.get': 'View Enforcement Center',
    'permissions.enforcements.post': 'Edit Enforcement',
    'permissions.enforcements.put': 'Add Enforcement',
    'permissions.enforcements.tasks.get': 'View Enforcement Tasks',
    'permissions.enforcements.delete': 'Delete Enforcement',
    'permissions.enforcements.run': 'Run Enforcement',

    'permissions.compliance': 'Cloud Asset Compliance',
    'permissions.compliance.get': 'View Cloud Asset Compliance',
    'permissions.compliance.post': 'Update score settings',
    'permissions.compliance.comments.post': 'Manage comments',

    'audit.session': 'User Session',
    'audit.session.login': 'Login',
    'audit.session.login.template': 'Login {status}',
    'audit.session.login_from': 'Login',
    'audit.session.login_from.template': 'Login {status} from {ip}',
    'audit.session.logout': 'Logout',
    'audit.session.logout.template': 'Logged out',
    'audit.session.failure': 'Login Failed',
    'audit.session.failure.template': 'Login failure attempt by {user_name}',
    'audit.session.failure_from': 'Login Failed',
    'audit.session.failure_from.template': 'Login failure attempt by {user_name} from {ip}',
    'audit.session.password_expiration': 'Password Expired',
    'audit.session.password_expiration.template': 'Password expired for user \'{user_name}\'',

    'audit.session.changed_password': 'Set Password',
    'audit.session.changed_password.template': 'Password set for user \'{user_name}\'',

    'audit.settings.users': 'User Management',
    'audit.settings.users.put': 'Add User',
    'audit.settings.users.put.template': 'Added user \'{user_name}\'',
    'audit.settings.users.post': 'Edit User',
    'audit.settings.users.post.template': 'Edited user \'{user_name}\'',
    'audit.settings.users.delete': 'Delete User',
    'audit.settings.users.delete.template': 'Deleted user \'{user_name}\'',

    'audit.settings.users.bulk': 'User Management',
    'audit.settings.users.bulk.delete': 'Delete User',
    'audit.settings.users.bulk.delete.template': 'Deleted {count} users',
    'audit.settings.users.bulk.assign_role': 'Assign Role',
    'audit.settings.users.bulk.assign_role.template': 'Assigned role \'{name}\' to {count} users',
    'audit.settings.users.assigned_role': 'Assign Role',
    'audit.settings.users.assigned_role.template': 'Assigned role {role} to user \'{user_name}\'',
    'audit.settings.users.add_external_user': 'Add External User',
    'audit.settings.users.add_external_user.template': 'External user mapping \'{user_name}\' from {source}',

    'audit.settings.roles': 'Role Management',
    'audit.settings.roles.put': 'Add Role',
    'audit.settings.roles.put.template': 'Added role \'{name}\'',
    'audit.settings.roles.post': 'Edit Role',
    'audit.settings.roles.post.template': 'Edited role \'{name}\'',
    'audit.settings.roles.delete': 'Delete Role',
    'audit.settings.roles.delete.template': 'Deleted role \'{name}\'',

    'audit.settings': 'Settings Management',
    'audit.settings.reset_api_key': 'Reset API Key',
    'audit.settings.reset_api_key.template': 'Reset API key',
    'audit.settings.run_manual_discovery': 'Run Manual Discovery',
    'audit.settings.run_manual_discovery.template': 'Ran manual discovery',
    'audit.settings.stop_research_phase': 'Stop Discovery',
    'audit.settings.stop_research_phase.template': 'Stopped discovery',

    'audit.settings.plugins': 'Settings Management',
    'audit.settings.plugins.post': 'Edit Settings',
    'audit.settings.plugins.post.template': 'Edited {config_name}',

    'audit.settings.configuration': 'Administration',
    'audit.settings.configuration.execute': 'Execute Config Script',
    'audit.settings.configuration.execute.template': 'Executed configuration script',
    'audit.settings.configuration.upload_file': 'Upload Config Script',
    'audit.settings.configuration.upload_file.template': 'Uploaded configuration script',

    'audit.settings.users.tokens': 'User Management',
    'audit.settings.users.tokens.generate': 'Password Reset Link',
    'audit.settings.users.tokens.generate.template': 'Password reset link generated for user \'{user_name}\' ',
    'audit.settings.users.tokens.notify': 'Send Password Reset Link',
    'audit.settings.users.tokens.notify.template': 'Password reset link sent for user \'{user_name}\' ',

    'audit.self': 'Account Management',
    'audit.self.password': 'Change Password',
    'audit.self.password.template': 'Changed password',
    'audit.self.preferences': 'Edit Default Columns',
    'audit.self.preferences.template': 'Edited default columns',

    'audit.settings.system_default_columns': 'Edit System Default',
    'audit.settings.system_default_columns.template': 'Edited system default view',

    'audit.discovery': 'Discovery',
    'audit.discovery.start': 'Discovery Started',
    'audit.discovery.start.template': 'Discovery cycle started',
    'audit.discovery.start_phase': 'Discovery Phase Started',
    'audit.discovery.start_phase.template': 'Discovery phase \'{phase}\' started',
    'audit.discovery.complete_phase': 'Discovery Phase Ended',
    'audit.discovery.complete_phase.template': 'Discovery phase \'{phase}\' ended',
    'audit.discovery.complete': 'Discovery Ended',
    'audit.discovery.complete.template': 'Discovery cycle ended',
    'audit.discovery.tag_reimaged': 'Tag Reimaged Devices',
    'audit.discovery.tag_reimaged.template': '{count} reimaged devices were tagged',

    'audit.custom_discovery': 'Custom Discovery',
    'audit.custom_discovery.fetch': 'Custom Discovery Fetch',
    'audit.custom_discovery.fetch.template': 'Custom Discovery fetch for \'{adapter}\'',
    'audit.custom_discovery.clean': 'Custom Discovery Clean',
    'audit.custom_discovery.clean.template': 'Custom Discovery clean for \'{adapter}\'',

    'audit.connection_custom_discovery': 'Custom Discovery',
    'audit.connection_custom_discovery.fetch': 'Custom Discovery Fetch',
    'audit.connection_custom_discovery.fetch.template': 'Custom Discovery fetch for \'{adapter}\' '
                                                        'with connection ID {client_id}',
    'audit.connection_custom_discovery.clean': 'Custom Discovery Clean',
    'audit.connection_custom_discovery.clean.template': 'Custom Discovery clean for \'{adapter}\'',

    'audit.custom_history': 'Historical Snapshot',
    'audit.custom_history.start': 'Save History Started',
    'audit.custom_history.start.template': 'Saving historical snapshot started',
    'audit.custom_history.end': 'Save History Ended',
    'audit.custom_history.end.template': 'Saving historical snapshot ended',

    'audit.custom_correlation': 'Correlation',
    'audit.custom_correlation.start': 'Correlation Started',
    'audit.custom_correlation.start.template': 'Correlation started',
    'audit.custom_correlation.end': 'Correlation Ended',
    'audit.custom_correlation.end.template': 'Correlation ended',

    'audit.getting_started': 'Getting Started',
    'audit.getting_started.complete_phase': 'Getting Started Phase Completed',
    'audit.getting_started.complete_phase.template': 'Getting Started phase \'{phase}\' completed',
    'audit.getting_started.complete': 'Getting Started Completed',
    'audit.getting_started.complete.template': 'Getting Started completed',

    'audit.instances': 'Instances',
    'audit.instances.post': 'Edit Instance',
    'audit.instances.post.template': 'Edited instance \'{node_name}\'',
    'audit.instances.node_update_name': 'Edit Instance',
    'audit.instances.node_update_name.template': 'Renamed instance \'{node_name}\'  to \'{update_node_name}\'',
    'audit.instances.node_update_hostname': 'Edit Instance',
    'audit.instances.node_update_hostname.template': 'Renamed hostname  \'{hostname}\' to \'{update_hostname}\''
                                                     ' on instance \'{node_name}\' ',
    'audit.instances.node_update_status': 'Edit Instance',
    'audit.instances.node_update_status.template': '{status} instance \'{node_name}\'',
    'audit.instances.node_update_indication': 'Edit Instance',
    'audit.instances.node_update_indication.template': 'Instance indication {update_indication} '
                                                       'on instance \'{node_name}\' ',

    'audit.reports': 'Reports',
    'audit.reports.put': 'Add Report',
    'audit.reports.put.template': 'Added {private} report \'{name}\'',
    'audit.reports.post': 'Edit Report',
    'audit.reports.post.template': 'Edited {private} report \'{name}\'',
    'audit.reports.delete': 'Delete Report',
    'audit.reports.delete.template': 'Deleted {count} reports',
    'audit.reports.download': 'Download Report',
    'audit.reports.download.template': 'Downloaded {private} report \'{name}\'',
    'audit.reports.send_email': 'Manual Sent Report',
    'audit.reports.send_email.template': 'Manually sent {private} report \'{name}\'',
    'audit.reports.trigger': 'Sent Report',
    'audit.reports.trigger.template': 'Report \'{name}\' sent',

    'audit.adapters': 'Adapters',
    'audit.adapters.complete': 'Fetch Ended',
    'audit.adapters.complete.template': 'Fetched {users_count} users and {devices_count} devices for adapter '
                                        '\'{adapter}\' with connection ID {client_id}. Duration: {duration}',
    'audit.adapters.start': 'Fetch Started',
    'audit.adapters.start.template': 'Fetch for adapter \'{adapter}\' with connection ID \'{client_id}\' started.',
    'audit.adapters.clean': 'Cleanup',
    'audit.adapters.clean.template': 'Removed {count} {asset} from adapter \'{adapter}\'',
    'audit.adapters.post': 'Edit Advanced Settings',
    'audit.adapters.post.template': 'Edited {config_name} for adapter {adapter_name}'
                                    ' Old configuration:{current_settings}.'
                                    ' New configuration:{updated_settings}',
    'audit.adapters.<adapter_name>.connections': 'Adapters',
    'audit.adapters.<adapter_name>.connections.put': 'Add Connection',
    'audit.adapters.<adapter_name>.connections.put.template':
    'Added new connection for adapter \'{adapter_name}\' with connection ID {client_id}',
    'audit.adapters.<adapter_name>.connections.post': 'Edit Connection',
    'audit.adapters.<adapter_name>.connections.post.template': 'Edited adapter \'{adapter_name}\' '
                                                               'with connection ID {client_id}.'
                                                               ' Old configuration:{current_client_info}.'
                                                               ' New configuration:{updated_client_info}',
    'audit.adapters.<adapter_name>.connections.delete': 'Delete Connection',
    'audit.adapters.<adapter_name>.connections.delete.template': 'Deleted adapter \'{adapter_name}\' '
                                                                 'with connection ID {client_id}',

    'audit.adapters.failure': 'Connection Failure',
    'audit.adapters.failure.template': 'Connection failure for adapter \'{adapter}\' '
                                       'with connection ID {client_id}. Error: {error}',

    'audit.adapters.skip': 'Fetch Skipped',
    'audit.adapters.skip.template': 'Fetch skipped for adapter \'{adapter}\' with connection ID {client_id}'
                                    ' - Tunnel is disconnected',

    'audit.adapters.connected': 'Adapter Connected',
    'audit.adapters.connected.template': 'Adapter \'{adapter}\' connected via tunnel',
    'audit.adapters.disconnected': 'Adapter Disconnected',
    'audit.adapters.disconnected.template': 'Adapter \'{adapter}\' disconnected from tunnel',

    'audit.enforcements': 'Enforcements',
    'audit.enforcements.put': 'Add Enforcement',
    'audit.enforcements.put.template': 'Added enforcement \'{name}\'',
    'audit.enforcements.post': 'Edit Enforcement',
    'audit.enforcements.post.template': 'Edited enforcement \'{name}\'',
    'audit.enforcements.delete': 'Delete Enforcement',
    'audit.enforcements.delete.template': 'Deleted {deleted} enforcements',
    'audit.enforcements.start': 'Enforcement Started',
    'audit.enforcements.start.template': 'Enforcement \'{enforcement}\' with task ID {task} started',
    'audit.enforcements.complete': 'Enforcement Ended',
    'audit.enforcements.complete.template': 'Enforcement \'{enforcement}\' with task ID {task} completed',
    'audit.enforcements.trigger': 'Run Enforcement',
    'audit.enforcements.trigger.template': 'Executed enforcement \'{name}\'',
    'audit.enforcements.update_tags': 'Update Tags',
    'audit.enforcements.update_tags.template': 'Enforcement \'{enforcement}\' updated tags',

    'audit.devices.views': 'Device Saved Queries',
    'audit.devices.views.put': 'Create Saved Query',
    'audit.devices.views.put.template': 'Created saved query {name}',
    'audit.devices.views.post': 'Edit Saved Query',
    'audit.devices.views.post.template': 'Edited saved query {name}',
    'audit.devices.views.delete': 'Delete Saved Query',
    'audit.devices.views.delete.template': 'Deleted {count} saved queries',
    'audit.devices.views.view': 'Delete Saved Query',
    'audit.devices.views.view.template': 'Deleted saved query \'{name}\'',
    'audit.devices.views.publish': 'Set Query Access',
    'audit.devices.views.publish.template': 'Set the access of query \'{name}\' to public',

    'audit.users.views': 'User Saved Query',
    'audit.users.views.put': 'Create Saved Query',
    'audit.users.views.put.template': 'Created saved query \'{name}\'',
    'audit.users.views.post': 'Edit Saved Query',
    'audit.users.views.post.template': 'Edited saved query \'{name}\'',
    'audit.users.views.delete': 'Delete Saved Query',
    'audit.users.views.delete.template': 'Deleted {count} saved queries',
    'audit.users.views.view': 'Delete Saved Query',
    'audit.users.views.view.template': 'Deleted saved query \'{name}\'',
    'audit.users.views.publish': 'Set Query Access',
    'audit.users.views.publish.template': 'Set the access of query \'{name}\' to public',

    'audit.dashboard': 'Dashboard',
    'audit.dashboard.delete': 'Delete Space',
    'audit.dashboard.delete.template': 'Deleted dashboard space \'{space_name}\'',
    'audit.dashboard.post': 'Add Space',
    'audit.dashboard.post.template': 'Added dashboard space \'{name}\'',
    'audit.dashboard.changed_name': 'Edit Space',
    'audit.dashboard.changed_name.template': 'Renamed dashboard space \'{before_space_name}\' to \'{space_name}\'',
    'audit.dashboard.changed_permissions': 'Edit Space',
    'audit.dashboard.changed_permissions.template': 'Modified the permissions of space \'{space_name}\'',
    'audit.dashboard.reorder': 'Reorder Space',
    'audit.dashboard.reorder.template': 'Reordered charts on space {\'{space_name}\'',
    'audit.dashboard.charts': 'Dashboard',
    'audit.dashboard.charts.put': 'Add Chart',
    'audit.dashboard.charts.put.template': 'Added chart \'{chart_name}\' of type {chart_type}'
                                           ' on space \'{space_name}\'',
    'audit.dashboard.charts.post': 'Edit Chart',
    'audit.dashboard.charts.post.template': 'Edited chart \'{chart_name}\' on space \'{space_name}\'',
    'audit.dashboard.charts.delete': 'Delete Chart',
    'audit.dashboard.charts.delete.template': 'Deleted chart \'{chart_name}\' from space \'{space_name}\'',
    'audit.dashboard.charts.export_csv': 'Export CSV',
    'audit.dashboard.charts.export_csv.template': 'Exported chart \'{chart_name}\' to CSV',

    'audit.dashboard.charts.move': 'Move Chart',
    'audit.dashboard.charts.move.template':
    'Moved chart \'{chart_name}\' from space \'{source_space_name}\' to space \'{target_space_name}\'',

    'audit.devices': 'Devices',
    'audit.devices.enforce': 'Run Enforcement',
    'audit.devices.enforce.template': 'Executed enforcement \'{name}\'',
    'audit.devices.csv': 'Export CSV',
    'audit.devices.csv.template': 'Exported to CSV',
    'audit.devices.manual_link': 'Link',
    'audit.devices.manual_link.template': 'Linked {count} devices',
    'audit.devices.manual_unlink': 'Link',
    'audit.devices.manual_unlink.template': 'Unlinked {count} devices',
    'audit.devices.delete': 'Delete Device',
    'audit.devices.delete.template': 'Deleted {count} devices',
    'audit.devices.custom': 'Add Custom Data',
    'audit.devices.custom.template': 'Added custom data',
    'audit.devices.notes': 'Edit Note',
    'audit.devices.notes.template': 'Edited notes',
    'audit.devices.labels': 'Edit Tags',
    'audit.devices.labels.template': 'Edited tags',
    'audit.devices.tasks_csv': 'Export CSV',
    'audit.devices.tasks_csv.template': 'Exported enforcement tasks for device to CSV',

    'audit.users': 'Users',
    'audit.users.enforce': 'Run Enforcement',
    'audit.users.enforce.template': 'Executed enforcement \'{name}\'',
    'audit.users.csv': 'Export CSV',
    'audit.users.csv.template': 'Exported to CSV',
    'audit.users.manual_link': 'Link',
    'audit.users.manual_link.template': 'Linked {count} users',
    'audit.users.manual_unlink': 'Link',
    'audit.users.manual_unlink.template': 'Unlinked {count} users',
    'audit.users.delete': 'Delete User',
    'audit.users.delete.template': 'Deleted {count} users',
    'audit.users.custom': 'Add Custom Data',
    'audit.users.custom.template': 'Added custom data',
    'audit.users.notes': 'Edit Note',
    'audit.users.notes.template': 'Edited notes',
    'audit.users.labels': 'Edit Tags',
    'audit.users.labels.template': 'Edited tags',
    'audit.users.tasks_csv': 'Export CSV',
    'audit.users.tasks_csv.template': 'Exported enforcement tasks for user to CSV',

    'audit.compliance': 'Cloud Asset Compliance',
    'audit.compliance.csv': 'Export CSV',
    'audit.compliance.csv.template': 'Exported to CSV compliance \'{name}\'',
    'audit.compliance.send_email': 'Send Email',
    'audit.compliance.send_email.template': 'Compliance {cis_title} results sent by email',
    'audit.compliance.add_comment': 'Add Comment',
    'audit.compliance.add_comment.template': 'Added comment for rule \'{section}\' on compliance \'{name}\'',
    'audit.compliance.edit_comments': 'Edit Comment',
    'audit.compliance.edit_comments.template': 'Edited comment for rule \'{section}\' on compliance \'{name}\'',
    'audit.compliance.delete_comments': 'Delete Comment',
    'audit.compliance.delete_comments.template':
        'Deleted comment for rule \'{section}\' on compliance \'{name}\'',

    'audit.tunnel': 'Tunnel',
    'audit.tunnel.connected': 'Tunnel Connected',
    'audit.tunnel.connected.template': 'Tunnel is connected',
    'audit.tunnel.disconnected': 'Tunnel Disconnected',
    'audit.tunnel.disconnected.template': 'Tunnel is disconnected',

    'audit.compliance.rules': 'Updated Scoring Rules',
    'audit.compliance.rules.template': 'Updated scoring rules for compliance {cis_title}',
    'audit.compliance.create_jira': 'Create Jira Issue',
    'audit.compliance.create_jira.template': 'Jira issue created for compliance {cis_title}',

    'audit.certificate': 'Certificate Settings',
    'audit.certificate.certificate_settings': 'Edit Settings',
    'audit.certificate.certificate_settings.template': 'Edited Certificate Settings',
    'audit.certificate.global_ssl': 'Import Certificate',
    'audit.certificate.global_ssl.template': 'Public and private certificate was imported',
    'audit.certificate.csr': 'Generate CSR',
    'audit.certificate.csr.template': 'CSR was generated',
    'audit.certificate.import_cert': 'Import CSR',
    'audit.certificate.import_cert.template': 'CSR was imported',
    'audit.certificate.cancel_csr': 'Cancel CSR',
    'audit.certificate.cancel_csr.template': 'CSR was canceled',
    'audit.certificate.reset_to_defaults': 'Restore Default',
    'audit.certificate.reset_to_defaults.template': 'Restored certificate to system default',

    'audit.backup': 'Backup',
    'audit.backup.start': 'Start Backup',
    'audit.backup.start.template': 'Initiated backup process {include_devices_users_data} {include_history}',
    'audit.backup.skip': 'Backup Skipped',
    'audit.backup.skip.template': 'Backup skipped: {cause}',
    'audit.backup.failure': 'Backup Failure',
    'audit.backup.failure.template': 'Backup failed: {cause}',
    'audit.backup.backup_file_ready': 'Start Copy',
    'audit.backup.backup_file_ready.template': 'Start copying backup file - '
                                               'size {file_size_mb}MB creation time was {duration}',

    'audit.restore': 'Backup',
    'audit.restore.restored': 'Restore Backup',
    'audit.restore.restored.template': 'Restore from backup file \'{filename}\'',

    'audit.backup.upload.start': 'Start Copy',
    'audit.backup.upload.start.template': 'Start Uploading backup file name {file_name} to {repo} repository ',
    'audit.backup.upload.completed': 'End Copy',
    'audit.backup.upload.completed.template': 'Completed Uploading backup file name {file_name} '
                                              'to {repo} repository ',
}
