import datetime

from axonius.fields import Field
from axonius.devices.device_adapter import DeviceAdapter


# pylint: disable=too-many-instance-attributes
class SpiceworkDevice(DeviceAdapter):
    asset_tag = Field(str, 'Asset Tag')
    auto_tag = Field(str, 'Auto Tag')
    avatar_id = Field(str, 'Avatar Id')
    b_asset_tag = Field(str, 'B Asset Tag')
    b_description = Field(str, 'B Description')
    b_device_type = Field(str, 'B Device Type')
    b_location = Field(str, 'B Location')
    b_manufacturer = Field(str, 'B Manufacturer')
    b_model = Field(str, 'B Model')
    b_name = Field(str, 'B Name')
    b_primary_owner_name = Field(str, 'B Primary Owner Name')
    b_serial_number = Field(str, 'B Serial Number')
    bios_date = Field(datetime.datetime, 'Bios Date')
    c_purchase_date = Field(datetime.datetime, 'C Purchase Date')
    c_purchase_price = Field(str, 'C Purchase Price')
    created_on = Field(datetime.datetime, 'Created On')
    device_type = Field(str, 'Device Type')
    domain_name = Field(str, 'Domain Name')
    domain_role = Field(str, 'Domain Role')
    error_alert_count = Field(int, 'Error Alert Count')
    exclude_tag = Field(str, 'Exclude Tag')
    install_date = Field(datetime.datetime, 'Install Date')
    ip_comparable = Field(int, 'Ip Comparable')
    last_backup_time = Field(str, 'Last Backup Time')
    last_boot_up_time = Field(str, 'Last Boot Up Time')
    last_qrcode_time = Field(str, 'Last QRcode Time')
    last_scan_time = Field(str, 'Last Scan Time')
    location = Field(str, 'Location')
    management_oid = Field(str, 'Management Oid')
    manually_added = Field(str, 'Manually Added')
    mdm_service_id = Field(str, 'MDM Service Id')
    memory = Field(int, 'Memory')
    number_of_licensed_users = Field(str, 'Number Of Licensed Users')
    number_of_processors = Field(str, 'Number Of Processors')
    offline_at = Field(datetime.datetime, 'Offline At')
    online_at = Field(datetime.datetime, 'Online At')
    open_ticket_count = Field(str, 'Open Ticket Count')
    page_count = Field(str, 'Page Count')
    port_scan_results = Field(str, 'Port Scan Results')
    processor_architecture = Field(str, 'Processor Architecture')
    processor_type = Field(str, 'Processor Type')
    product_categories = Field(str, 'Product Categories')
    product_info_id = Field(str, 'Product Info Id')
    raw_manufacturer = Field(str, 'Raw Manufacturer')
    raw_model = Field(str, 'Raw Model')
    raw_operating_system = Field(str, 'Raw Operating System')
    raw_processor_type = Field(str, 'Raw Processor Type')
    raw_serial_number = Field(str, 'Raw Serial Number')
    reported_by_id = Field(str, 'Reported By Id')
    scan_preferences = Field(str, 'Scan Preferences')
    scan_state = Field(str, 'Scan State')
    server_name = Field(str, 'Server Name')
    service_pack_major_version = Field(str, 'Service Pack Major Version')
    service_pack_minor_version = Field(str, 'Service Pack Minor Version')
    site_id = Field(int, 'Site Id')
    spice_version = Field(int, 'Spice Version')
    swid = Field(str, 'SWID')
    user_id = Field(str, 'User Id')
    user_primary = Field(str, 'User Primary')
    user_tag = Field(str, 'User Tag')
    version = Field(str, 'Version')
    virtual_machine = Field(str, 'VM')
    vpro_level = Field(int, 'Vpro Level')
    warning_alert_count = Field(int, 'Warning Alert Count')
    windows_product_id = Field(str, 'Windows Product_id')
    windows_user = Field(str, 'Windows User')
    user_primary = Field(bool, 'Primary User')
