# MAX_NUMBER_OF_AGENTS must be divided by AGENTS_PER_PAGE
AGENTS_PER_PAGE = 200
MAX_NUMBER_OF_AGENTS = 20000000
MAX_NUMBER_OF_POLICIES = 100000

DEFAULT_API_PORT = 3121

API_URL_PREFIX = 'st/console/api/v1.0'

API_AGENTS_SUFFIX = 'agents'
API_POLICIES_SUFFIX = 'policies'

EXTRA_POLICY_INFO = 'extra_policy'
