package domain

import (
	"context"
	"github.com/iancoleman/strcase"
	"strings"
)

// TODO: consider just using modelgen
type AdapterType string

const (
	AdapterTypeUnknown                        AdapterType = "UNKNOWN"
	AdapterTypeCustom                         AdapterType = "CUSTOM"
	AdapterTypeAbsolute                       AdapterType = "ABSOLUTE"
	AdapterTypeActiveDirectory                AdapterType = "ACTIVE_DIRECTORY"
	AdapterTypeAirwatch                       AdapterType = "AIRWATCH"
	AdapterTypeAirwave                        AdapterType = "AIRWAVE"
	AdapterTypeAlertlogic                     AdapterType = "ALERTLOGIC"
	AdapterTypeAlibaba                        AdapterType = "ALIBABA"
	AdapterTypeAnsibleTower                   AdapterType = "ANSIBLE_TOWER"
	AdapterTypeAqua                           AdapterType = "AQUA"
	AdapterTypeAristaEos                      AdapterType = "ARISTA_EOS"
	AdapterTypeArmis                          AdapterType = "ARMIS"
	AdapterTypeArsenal                        AdapterType = "ARSENAL"
	AdapterTypeAruba                          AdapterType = "ARUBA"
	AdapterTypeAutomox                        AdapterType = "AUTOMOX"
	AdapterTypeAws                            AdapterType = "AWS"
	AdapterTypeAzureAd                        AdapterType = "AZURE_AD"
	AdapterTypeAzure                          AdapterType = "AZURE"
	AdapterTypeBamboohr                       AdapterType = "BAMBOOHR"
	AdapterTypeBigfix                         AdapterType = "BIGFIX"
	AdapterTypeBigfixInventory                AdapterType = "BIGFIX_INVENTORY"
	AdapterTypeBitdefender                    AdapterType = "BITDEFENDER"
	AdapterTypeBitlocker                      AdapterType = "BITLOCKER"
	AdapterTypeBitsight                       AdapterType = "BITSIGHT"
	AdapterTypeBlackberryUem                  AdapterType = "BLACKBERRY_UEM"
	AdapterTypeBluecat                        AdapterType = "BLUECAT"
	AdapterTypeBomgar                         AdapterType = "BOMGAR"
	AdapterTypeCaCmdb                         AdapterType = "CA_CMDB"
	AdapterTypeCaSpectrum                     AdapterType = "CA_SPECTRUM"
	AdapterTypeCarbonblackDefense             AdapterType = "CARBONBLACK_DEFENSE"
	AdapterTypeCarbonblackResponse            AdapterType = "CARBONBLACK_RESPONSE"
	AdapterTypeCensys                         AdapterType = "CENSYS"
	AdapterTypeCheckpointr90                  AdapterType = "CHECKPOINTR90"
	AdapterTypeChef                           AdapterType = "CHEF"
	AdapterTypeCherwell                       AdapterType = "CHERWELL"
	AdapterTypeCisco                          AdapterType = "CISCO"
	AdapterTypeCiscoAmp                       AdapterType = "CISCO_AMP"
	AdapterTypeCiscoFirepowerManagementCenter AdapterType = "CISCO_FIREPOWER_MANAGEMENT_CENTER"
	AdapterTypeCiscoIse                       AdapterType = "CISCO_ISE"
	AdapterTypeCiscoMeraki                    AdapterType = "CISCO_MERAKI"
	AdapterTypeCiscoPrime                     AdapterType = "CISCO_PRIME"
	AdapterTypeCiscoStealthwatch              AdapterType = "CISCO_STEALTHWATCH"
	AdapterTypeCiscoUcm                       AdapterType = "CISCO_UCM"
	AdapterTypeCiscoUcsm                      AdapterType = "CISCO_UCSM"
	AdapterTypeCiscoUmberella                 AdapterType = "CISCO_UMBERELLA"
	AdapterTypeClaroty                        AdapterType = "CLAROTY"
	AdapterTypeClearpass                      AdapterType = "CLEARPASS"
	AdapterTypeCloudflare                     AdapterType = "CLOUDFLARE"
	AdapterTypeCloudPassage                   AdapterType = "CLOUD_PASSAGE"
	AdapterTypeCode42                         AdapterType = "CODE42"
	AdapterTypeCounterAct                     AdapterType = "COUNTER_ACT"
	AdapterTypeCrowdStrike                    AdapterType = "CROWD_STRIKE"
	AdapterTypeCscGlobal                      AdapterType = "CSC_GLOBAL"
	AdapterTypeCsv                            AdapterType = "CSV"
	AdapterTypeCybereason                     AdapterType = "CYBEREASON"
	AdapterTypeCycognito                      AdapterType = "CYCOGNITO"
	AdapterTypeCylance                        AdapterType = "CYLANCE"
	AdapterTypeCynet                          AdapterType = "CYNET"
	AdapterTypeDatadog                        AdapterType = "DATADOG"
	AdapterTypeDatto                          AdapterType = "DATTO"
	AdapterTypeDeepSecurity                   AdapterType = "DEEP_SECURITY"
	AdapterTypeDefenderAtp                    AdapterType = "DEFENDER_ATP"
	AdapterTypeDesktopCentral                 AdapterType = "DESKTOP_CENTRAL"
	AdapterTypeDevice42                       AdapterType = "DEVICE42"
	AdapterTypeDigicertCertcentral            AdapterType = "DIGICERT_CERTCENTRAL"
	AdapterTypeDivvyCloud                     AdapterType = "DIVVY_CLOUD"
	AdapterTypeDropbox                        AdapterType = "DROPBOX"
	AdapterTypeDruva                          AdapterType = "DRUVA"
	AdapterTypeDuo                            AdapterType = "DUO"
	AdapterTypeDynatrace                      AdapterType = "DYNATRACE"
	AdapterTypeEclypsium                      AdapterType = "ECLYPSIUM"
	AdapterTypeEdgesscan                      AdapterType = "EDGESSCAN"
	AdapterTypeEndgame                        AdapterType = "ENDGAME"
	AdapterTypeEnsilo                         AdapterType = "ENSILO"
	AdapterTypeEpo                            AdapterType = "EPO"
	AdapterTypeEset                           AdapterType = "ESET"
	AdapterTypeEsx                            AdapterType = "ESX"
	AdapterTypeF5Icontrol                     AdapterType = "F5_ICONTROL"
	AdapterTypeFireEyeHx                      AdapterType = "FIRE_EYE_HX"
	AdapterTypeForcepointCsv                  AdapterType = "FORCEPOINT_CSV"
	AdapterTypeForeman                        AdapterType = "FOREMAN"
	AdapterTypeFortigate                      AdapterType = "FORTIGATE"
	AdapterTypeFreshService                   AdapterType = "FRESH_SERVICE"
	AdapterTypeGce                            AdapterType = "GCE"
	AdapterTypeGithub                         AdapterType = "GITHUB"
	AdapterTypeGoogleBigQuery                 AdapterType = "GOOGLE_BIG_QUERY"
	AdapterTypeGoogleMdm                      AdapterType = "GOOGLE_MDM"
	AdapterTypeGotoassit                      AdapterType = "GOTOASSIST"
	AdapterTypeGurdicore                      AdapterType = "GURDICORE"
	AdapterTypeGuardium                       AdapterType = "GUARDIUM"
	AdapterTypeHashicorp                      AdapterType = "HASHICORP"
	AdapterTypeHaveibeenpwned                 AdapterType = "HAVEIBEENPWNED"
	AdapterTypeHpNnmi                         AdapterType = "HP_NNMI"
	AdapterTypeHyperV                         AdapterType = "HYPER_V"
	AdapterTypeIbmTivoliTaddm                 AdapterType = "IBM_TIVOLI_TADDM"
	AdapterTypeIcinga                         AdapterType = "ICINGA"
	AdapterTypeIgar                           AdapterType = "IGAR"
	AdapterTypeIllusive                       AdapterType = "ILLUSIVE"
	AdapterTypeImperva                        AdapterType = "IMPERVA"
	AdapterTypeIndegy                         AdapterType = "INDEGY"
	AdapterTypeInfiniteSleep                  AdapterType = "INFINITE_SLEEP"
	AdapterTypeInfoblox                       AdapterType = "INFOBLOX"
	AdapterTypeIvantiSm                       AdapterType = "IVANTI_SM"
	AdapterTypeJamf                           AdapterType = "JAMF"
	AdapterTypeJSON                           AdapterType = "JSON"
	AdapterTypeJSONFile                       AdapterType = "JSON_FILE"
	AdapterTypeJumpcloud                      AdapterType = "JUMPCLOUD"
	AdapterTypeJuniper                        AdapterType = "JUNIPER"
	AdapterTypeJunos                          AdapterType = "JUNOS"
	AdapterTypeKaseya                         AdapterType = "KASEYA"
	AdapterTypeKasperskySc                    AdapterType = "KASPERSKY_SC"
	AdapterTypeLandesk                        AdapterType = "LANDESK"
	AdapterTypeLansweeper                     AdapterType = "LANSWEEPER"
	AdapterTypeLibernms                       AdapterType = "LIBERNMS"
	AdapterTypeLinuxSSH                       AdapterType = "LINUX_SSH"
	AdapterTypeLogrythm                       AdapterType = "LOGRYTHM"
	AdapterTypeMaas360                        AdapterType = "MAAS360"
	AdapterTypeMalwarebytes                   AdapterType = "MALWAREBYTES"
	AdapterTypeMasscan                        AdapterType = "MASSCAN"
	AdapterTypeMedigate                       AdapterType = "MEDIGATE"
	AdapterTypeMenAndMice                     AdapterType = "MEN_AND_MICE"
	AdapterTypeMinerva                        AdapterType = "MINERVA"
	AdapterTypeMobiControl                    AdapterType = "MOBI_CONTROL"
	AdapterTypeMobileIron                     AdapterType = "MOBILE_IRON"
	AdapterTypeMssql                          AdapterType = "MSSQL"
	AdapterTypeNessus                         AdapterType = "NESSUS"
	AdapterTypeNessusCsv                      AdapterType = "NESSUS_CSV"
	AdapterTypeNetbox                         AdapterType = "NETBOX"
	AdapterTypeNetbrain                       AdapterType = "NETBRAIN"
	AdapterTypeNetskope                       AdapterType = "NETSKOPE"
	AdapterTypeNexpose                        AdapterType = "NEXPOSE"
	AdapterTypeNimbul                         AdapterType = "NIMBUL"
	AdapterTypeNmap                           AdapterType = "NMAP"
	AdapterTypeNutanix                        AdapterType = "NUTANIX"
	AdapterTypeObserveit                      AdapterType = "OBSERVEIT"
	AdapterTypeObservium                      AdapterType = "OBSERVIUM"
	AdapterTypeOfficeScan                     AdapterType = "OFFICE_SCAN"
	AdapterTypeOkta                           AdapterType = "OKTA"
	AdapterTypeOmnivista                      AdapterType = "OMNIVISTA"
	AdapterTypeOpenstack                      AdapterType = "OPENSTACK"
	AdapterTypeOpswat                         AdapterType = "OPSWAT"
	AdapterTypeOracleCloud                    AdapterType = "ORACLE_CLOUD"
	AdapterTypeOracleVM                       AdapterType = "ORACLE_VM"
	AdapterTypeOrca                           AdapterType = "ORCA"
	AdapterTypePacketfence                    AdapterType = "PACKETFENCE"
	AdapterTypePaloaltoCortex                 AdapterType = "PALOALTO_CORTEX"
	AdapterTypePaloaltoPanorama               AdapterType = "PALOALTO_PANORAMA"
	AdapterTypePaloaltoXdr                    AdapterType = "PALOALTO_XDR"
	AdapterTypePkware                         AdapterType = "PKWARE"
	AdapterTypePreempt                        AdapterType = "PREEMPT"
	AdapterTypePromisec                       AdapterType = "PROMISEC"
	AdapterTypeProxmox                        AdapterType = "PROXMOX"
	AdapterTypePuppet                         AdapterType = "PUPPET"
	AdapterTypeQcore                          AdapterType = "QCORE"
	AdapterTypeQualys                         AdapterType = "QUALYS"
	AdapterTypeQuestKace                      AdapterType = "QUEST_KACE"
	AdapterTypeRandori                        AdapterType = "RANDORI"
	AdapterTypeRedcanary                      AdapterType = "REDCANARY"
	AdapterTypeRedcloak                       AdapterType = "REDCLOAK"
	AdapterTypeRedseal                        AdapterType = "REDSEAL"
	AdapterTypeRiskIq                         AdapterType = "RISK_IQ"
	AdapterTypeRiverbed                       AdapterType = "RIVERBED"
	AdapterTypeRumble                         AdapterType = "RUMBLE"
	AdapterTypeSaltstack                      AdapterType = "SALTSTACK"
	AdapterTypeSaltstackEnterprise            AdapterType = "SALTSTACK_ENTERPRISE"
	AdapterTypeSamange                        AdapterType = "SAMANGE"
	AdapterTypeSccm                           AdapterType = "SCCM"
	AdapterTypeScep                           AdapterType = "SCEP"
	AdapterTypeSecdo                          AdapterType = "SECDO"
	AdapterTypeSentinelone                    AdapterType = "SENTINELONE"
	AdapterTypeServicenow                     AdapterType = "SERVICENOW"
	AdapterTypeShoadan                        AdapterType = "SHOADAN"
	AdapterTypeSignalsciences                 AdapterType = "SIGNALSCIENCES"
	AdapterTypeSkybox                         AdapterType = "SKYBOX"
	AdapterTypeSnipeit                        AdapterType = "SNIPEIT"
	AdapterTypeSnow                           AdapterType = "SNOW"
	AdapterTypeSoftlayer                      AdapterType = "SOFTLAYER"
	AdapterTypeSolarwindsOrion                AdapterType = "SOLARWINDS_ORION"
	AdapterTypeSophos                         AdapterType = "SOPHOS"
	AdapterTypeSpacewalk                      AdapterType = "SPACEWALK"
	AdapterTypeSpecops                        AdapterType = "SPECOPS"
	AdapterTypeSplunk                         AdapterType = "SPLUNK"
	AdapterTypeStresstest                     AdapterType = "STRESSTEST"
	AdapterTypeSymantec12                     AdapterType = "SYMANTEC"
	AdapterTypeSymantecAltris                 AdapterType = "SYMANTEC_ALTIRIS"
	AdapterTypeSymantecCcs                    AdapterType = "SYMANTEC_CCS"
	AdapterTypeSymantecCloudWorkload          AdapterType = "SYMANTEC_CLOUD_WORKLOAD"
	AdapterTypeSymantecDlp                    AdapterType = "SYMANTEC_DLP"
	AdapterTypeSymantecSepCloud               AdapterType = "SYMANTEC_SEP_CLOUD"
	AdapterTypeSysaid                         AdapterType = "SYSAID"
	AdapterTypeTanium                         AdapterType = "TANIUM"
	AdapterTypeTenableIo                      AdapterType = "TENABLE_IO"
	AdapterTypeTenableSecurityCenter          AdapterType = "TENABLE_SECURITY_CENTER"
	AdapterTypeToriihq                        AdapterType = "TORIIHQ"
	AdapterTypeTraianaLabMachines             AdapterType = "TRAIANA_LAB_MACHINES"
	AdapterTypeTripwireEnterprise             AdapterType = "TRIPWIRE_ENTERPRISE"
	AdapterTypeTruefort                       AdapterType = "TRUEFORT"
	AdapterTypeTwistlock                      AdapterType = "TWISTLOCK"
	AdapterTypeUnifi                          AdapterType = "UNIFI"
	AdapterTypeVcloudDirector                 AdapterType = "VCLOUD_DIRECTOR"
	AdapterTypeWazuh                          AdapterType = "WAZUH"
	AdapterTypeWebroot                        AdapterType = "WEBROOT"
	AdapterTypeWebscan                        AdapterType = "WEBSCAN"
	AdapterTypeWsus                           AdapterType = "WSUS"
	AdapterTypeZabbix                         AdapterType = "ZABBIX"
	AdapterTypeZscaler                        AdapterType = "ZSCALER"
)

func GetAdapterTypeByName(a string) string {
	return strcase.ToSnake(strings.TrimSuffix(a, "_adapter"))
}

type Adapter struct {
	Id         string
	Name       string
	Properties []string `pg:",array"`
	//Clients []AdapterClient
}

// A single Connection of an Adapter to a source of data
type AdapterClient struct{}

// AdapterRepository describes the interface for interacting with device
type AdapterRepository interface {
	FindAdapters(ctx context.Context, skip, limit int64) ([]Adapter, error)
	GetAdapter(ctx context.Context, id AdapterType) (Adapter, error)
	SaveAdapter(ctx context.Context, a Adapter) error
	DeleteAdapter(ctx context.Context, a AdapterType) error
}

type AdapterData interface {
	IsAdapterData()
}
