OBJECTS_PER_PAGE = 200
MAX_NUMBER_OF_OBJECTS = 20000000

DEFAULT_TOKEN_TYPE = 'Bearer'
DEFAULT_TOKEN_TIMEOUT_SEC = 10
TOKEN_EXPIRES_GAP_SEC = 60

API_URL_TOKEN_SUFFIX = 'oauth2/token'
API_URL_ASSETS_SUFFIX = 'v2/assets'
API_URL_USERS_SUFFIX = 'v2/users'

ASSET_TYPE = 'Assets'
USERS_TYPE = 'Users'
