CERTIFICATE_PER_PAGE = 200
MAX_NUMBER_OF_CERTIFICATES = 2000000

DEFAULT_ASYNC_CHUNKS = 50

URL_API_FORMAT = '{}://{}'

AUTHENTICATION_URL_SUFFIX = 'vedauth/authorize/oauth'

CERT_API_SUFFIX = 'vedsdk/certificates'
