client_details = {
    'host': '192.168.20.10',
    'port': 3780,
    'username': 'readonly-user',
    'password': 'Password2',
    'verify_ssl': False
}

SOME_DEVICE_ID = '11'

FETCHED_DEVICE_EXAMPLE = \
    {'hostname': 'nexpose', 'id': '11', 'last_seen': 'Mon, 15 Jan 2018 10:32:20 GMT',
     'network_interfaces': [{'ips': [], 'mac': '00:50:56:91:00:66'}],
     'os': {'bitness': 64, 'distribution': 'Ubuntu', 'type': 'Linux'},
     'raw': {'API': '3', 'addresses': [{'ip': '192.168.20.10', 'mac': '00:50:56:91:00:66'}],
             'assessedForPolicies': False, 'assessedForVulnerabilities': True,
             'history': [
                 {'date': '2017-12-20T22:13:22.104Z', 'scanId': 533, 'type': 'SCAN', 'version': 1},
                 {'date': '2018-01-15T10:32:20.653Z', 'scanId': 24757, 'type': 'SCAN', 'version': 2}],
             'hostName': 'nexpose', 'hostNames': [{'name': 'nexpose', 'source': 'other'}],
             'id': 11,
             'ids': [{'id': '4211CC00-09DB-EA6D-D57D-5D20F70DF102', 'source': 'dmidecode'}],
             'ip': '192.168.20.10',
             'links': [{'href': 'https://192.168.20.10:3780/api/3/assets/11', 'rel': 'self'},
                       {'href': 'https://192.168.20.10:3780/api/3/assets/11/software',
                        'rel': 'Software'},
                       {'href': 'https://192.168.20.10:3780/api/3/assets/11/files',
                        'rel': 'Files'},
                       {'href': 'https://192.168.20.10:3780/api/3/assets/11/users',
                        'rel': 'Users'},
                       {'href': 'https://192.168.20.10:3780/api/3/assets/11/user_groups',
                        'rel': 'User Groups'},
                       {'href': 'https://192.168.20.10:3780/api/3/assets/11/databases',
                        'rel': 'Databases'},
                       {'href': 'https://192.168.20.10:3780/api/3/assets/11/services',
                        'rel': 'Services'},
                       {'href': 'https://192.168.20.10:3780/api/3/assets/11/tags', 'rel': 'Tags'}],
             'mac': '00:50:56:91:00:66', 'os': 'Ubuntu Linux 16.04',
             'osFingerprint': {'architecture': 'x86_64', 'description': 'Ubuntu Linux 16.04',
                               'family': 'Linux', 'id': 4, 'product': 'Linux',
                               'systemName': 'Ubuntu Linux', 'vendor': 'Ubuntu',
                               'version': '16.04'}, 'rawRiskScore': 2836.88037,
             'riskScore': 2836.88037,
             'services': [
                 {
                     'configurations': [
                         {'name': 'ssh.banner', 'value': 'SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.2'},
                         {'name': 'ssh.protocol.version', 'value': '2.0'}],
                     'family': 'OpenSSH',
                     'links': [
                         {'href': 'https://192.168.20.10:3780/api/3/assets/11/services/tcp/22', 'rel': 'self'},
                         {'href': 'https://192.168.20.10:3780/api/3/assets/11/services/tcp/22/configurations',
                          'rel': 'Configurations'},
                         {'href': 'https://192.168.20.10:3780/api/3/assets/11/services/tcp/22/databases',
                          'rel': 'Databases'},
                         {'href': 'https://192.168.20.10:3780/api/3/assets/11/services/tcp/22/users',
                          'rel': 'Users'},
                         {'href': 'https://192.168.20.10:3780/api/3/assets/11/services/tcp/22/user_groups',
                          'rel': 'User Groups'},
                         {'href': 'https://192.168.20.10:3780/api/3/assets/11/services/tcp/22/web_applications',
                          'rel': 'Web Applications'}],
                     'name': 'SSH',
                     'port': 22,
                     'product': 'OpenSSH',
                     'protocol': 'tcp', 'vendor': 'OpenBSD',
                     'version': '7.2p2'}], 'type': 'guest',
             'userGroups': [{'id': 121, 'name': '_chrony'}, {'id': 4, 'name': 'adm'},
                            {'id': 29, 'name': 'audio'}, {'id': 34, 'name': 'backup'},
                            {'id': 2, 'name': 'bin'}, {'id': 24, 'name': 'cdrom'},
                            {'id': 107, 'name': 'crontab'}, {'id': 1, 'name': 'daemon'},
                            {'id': 20, 'name': 'dialout'}, {'id': 30, 'name': 'dip'},
                            {'id': 6, 'name': 'disk'}, {'id': 21, 'name': 'fax'},
                            {'id': 25, 'name': 'floppy'}, {'id': 60, 'name': 'games'},
                            {'id': 41, 'name': 'gnats'}, {'id': 106, 'name': 'input'},
                            {'id': 39, 'name': 'irc'}, {'id': 15, 'name': 'kmem'},
                            {'id': 38, 'name': 'list'}, {'id': 7, 'name': 'lp'},
                            {'id': 116, 'name': 'lpadmin'}, {'id': 110, 'name': 'lxd'},
                            {'id': 8, 'name': 'mail'}, {'id': 12, 'name': 'man'},
                            {'id': 111, 'name': 'messagebus'}, {'id': 113, 'name': 'mlocate'},
                            {'id': 109, 'name': 'netdev'}, {'id': 9, 'name': 'news'},
                            {'id': 1000, 'name': 'nexpose'}, {'id': 65534, 'name': 'nogroup'},
                            {'id': 115, 'name': 'ntp'}, {'id': 1001, 'name': 'nxpgsql'},
                            {'id': 37, 'name': 'operator'}, {'id': 46, 'name': 'plugdev'},
                            {'id': 120, 'name': 'postdrop'}, {'id': 119, 'name': 'postfix'},
                            {'id': 13, 'name': 'proxy'}, {'id': 0, 'name': 'root'},
                            {'id': 117, 'name': 'sambashare'}, {'id': 45, 'name': 'sasl'},
                            {'id': 42, 'name': 'shadow'}, {'id': 40, 'name': 'src'},
                            {'id': 114, 'name': 'ssh'}, {'id': 118, 'name': 'ssl-cert'},
                            {'id': 50, 'name': 'staff'}, {'id': 27, 'name': 'sudo'},
                            {'id': 3, 'name': 'sys'}, {'id': 108, 'name': 'syslog'},
                            {'id': 105, 'name': 'systemd-bus-proxy'},
                            {'id': 101, 'name': 'systemd-journal'},
                            {'id': 103, 'name': 'systemd-network'},
                            {'id': 104, 'name': 'systemd-resolve'},
                            {'id': 102, 'name': 'systemd-timesync'}, {'id': 26, 'name': 'tape'},
                            {'id': 5, 'name': 'tty'}, {'id': 100, 'name': 'users'},
                            {'id': 43, 'name': 'utmp'}, {'id': 10, 'name': 'uucp'},
                            {'id': 112, 'name': 'uuidd'}, {'id': 44, 'name': 'video'},
                            {'id': 22, 'name': 'voice'}, {'id': 33, 'name': 'www-data'}],
             'users': [{'id': 105, 'name': '_apt'},
                       {'fullName': 'Chrony daemon,,,', 'id': 114, 'name': '_chrony'},
                       {'fullName': 'backup', 'id': 34, 'name': 'backup'},
                       {'fullName': 'bin', 'id': 2, 'name': 'bin'},
                       {'fullName': 'daemon', 'id': 1, 'name': 'daemon'},
                       {'fullName': 'dnsmasq,,,', 'id': 109, 'name': 'dnsmasq'},
                       {'fullName': 'games', 'id': 5, 'name': 'games'},
                       {'fullName': 'Gnats Bug-Reporting System (admin)', 'id': 41,
                        'name': 'gnats'}, {'fullName': 'ircd', 'id': 39, 'name': 'irc'},
                       {'fullName': 'Mailing List Manager', 'id': 38, 'name': 'list'},
                       {'fullName': 'lp', 'id': 7, 'name': 'lp'}, {'id': 106, 'name': 'lxd'},
                       {'fullName': 'mail', 'id': 8, 'name': 'mail'},
                       {'fullName': 'man', 'id': 6, 'name': 'man'},
                       {'id': 107, 'name': 'messagebus'},
                       {'fullName': 'news', 'id': 9, 'name': 'news'},
                       {'fullName': 'nexpose,,,', 'id': 1000, 'name': 'nexpose'},
                       {'fullName': 'nobody', 'id': 65534, 'name': 'nobody'},
                       {'id': 110, 'name': 'ntp'},
                       {'fullName': 'NeXpose PostgreSQL User', 'id': 1001, 'name': 'nxpgsql'},
                       {'id': 113, 'name': 'postfix'},
                       {'fullName': 'proxy', 'id': 13, 'name': 'proxy'},
                       {'fullName': 'root', 'id': 0, 'name': 'root'}, {'id': 112, 'name': 'sshd'},
                       {'id': 111, 'name': 'statd'}, {'fullName': 'sync', 'id': 4, 'name': 'sync'},
                       {'fullName': 'sys', 'id': 3, 'name': 'sys'}, {'id': 104, 'name': 'syslog'},
                       {'fullName': 'systemd Bus Proxy,,,', 'id': 103,
                        'name': 'systemd-bus-proxy'},
                       {'fullName': 'systemd Network Management,,,', 'id': 101,
                        'name': 'systemd-network'},
                       {'fullName': 'systemd Resolver,,,', 'id': 102, 'name': 'systemd-resolve'},
                       {'fullName': 'systemd Time Synchronization,,,', 'id': 100,
                        'name': 'systemd-timesync'},
                       {'fullName': 'uucp', 'id': 10, 'name': 'uucp'},
                       {'id': 108, 'name': 'uuidd'},
                       {'fullName': 'www-data', 'id': 33, 'name': 'www-data'}],
             'vulnerabilities': {'critical': 0, 'exploits': 0, 'malwareKits': 0, 'moderate': 2,
                                 'severe': 4, 'total': 6}}, 'scanner': True}
