TEST_PROXY_STRING = 'https://10.0.230.207:8888'

TEST_STUNNEL_CREDS = {
    'PUBLIC_SSL_HOST_ADDR': '10.0.2.231',
    'PUBLIC_SSL_HOST_USER': 'sshuser',
    'PUBLIC_SSL_HOST_PASSW': 'sshpass',
    'PUBLIC_SSL_HOST_STUNNEL_LINK_PORT': 0,
    'LOCAL_STUNNEL_LINK_PORT': 6666,
    'HTTPS_PROXY': ''
}
