apiVersion: v1
kind: PersistentVolume
metadata:
  name: axonius-logs
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/logs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: axonius-data
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/DB
